add argument in python script and add requirement.txt
CIDCO-dev/PecheFantome pull request #25
Opened 2022-03-30 18:03 UTC by Ddoiron-cidco

add argument in python script and add requirement.txt

2022-03-30 20:41 UTC, glabmoris requested changes
Utiliser des noms explicites et bien formés pour les noms de fichier:
ValideRetrieved*.py  :  ça importe le fichier du DFO. je suggèrerais qqch comme import_dfo_data_*.py

- Il faudrait être consistant dans le langage...utiliser match_crabtraps.py au lieu de appariement.py

2022-03-30 20:45 UTC, glabmoris requested changes
Polissage requis

2022-03-30 20:45 UTC, glabmoris commented on ValideRetrieved.py
> +def main():
La main() sera appelée de la main implicite/explicite...il faudrait restructurer cette méthode qui fait beaucoup trop de choses.

2022-03-30 20:45 UTC, glabmoris commented on ValideRetrieved.py
> +def loar_arg():
Il ne faut pas utiliser des variables globales. Percoler les variables de la ligne de commande: les arguments de la ligne de commande deviennent les parametres des méthodes principales

2022-03-30 20:45 UTC, glabmoris commented on ValideRetrieved.py
> +  if sys.argv[1] == "-h":
Overkill... -h et --help suffisent amplement

2022-03-30 20:45 UTC, glabmoris commented on ValideRetrieved.py
> +def help():
Adapter les noms de fichier tel que décrit ci-haut

2022-03-31 13:50 UTC, Ddoiron-cidco commented on ValideRetrieved.py
> +def main():
la fonction maine as été renomé par main_script. 

Dominic semblais dire qu'il avais du travail a refaire dans le script principale. Je le laisse gerré la restructuration?

2022-03-31 13:56 UTC, Ddoiron-cidco commented on ValideRetrieved.py
> +def loar_arg():
les variable globalle ont été suprimmer et le tout as été ajouter comme argument a la fonction appeler

2022-03-31 13:57 UTC, Ddoiron-cidco commented on ValideRetrieved.py
> +  if sys.argv[1] == "-h":
correction effectuer

2022-04-11 16:20 UTC, glabmoris commented
@Ddoiron-cidco 
Il faudrait résoudre les conflits pour pouvoir merger

2022-04-11 16:27 UTC, Ddoiron-cidco commented
il n'y avais aucun conflit quand j'ai pousser ce pull request. 

Le conflit a été crée car un pull request plus récent as été accepter avant ce pull request qui étais plus vieux.

2022-04-11 16:34 UTC, closed without merging