modification
CIDCO-dev/PecheFantome pull request #27
Opened 2022-04-11 16:51 UTC by Ddoiron-cidco

modification des nom des script python et ajoute de la section d'aide

2022-04-13 16:52 UTC, glabmoris requested changes
Besoin de refactoriser

2022-04-13 16:52 UTC, glabmoris commented on match_crabtraps.py
> +if len(sys.argv) == 5:
Ceci est la vraie main.

2022-04-13 16:52 UTC, glabmoris commented on import_dfo_data.py
> +if len(sys.argv) == 6:
Ceci est la vraie main.

2022-04-13 16:52 UTC, glabmoris commented on import_dfo_data.py
> +def loar_arg():
Ceci est un mauvais pattern. Il n'Est pas nécessaire de créer une méthode pour assigner des arguments, surtout pas à des variables globales.

2022-04-13 16:52 UTC, glabmoris commented on import_dfo_data.py
> +def main_script(arg_host, arg_user, arg_password, arg_database, arg_filename):
Ceci devrait être la main, pas une fonction à part.

2022-04-20 18:04 UTC, Ddoiron-cidco commented on match_crabtraps.py
> +if len(sys.argv) == 5:
je comprend pas ce que tu veut dire

2022-04-20 18:04 UTC, Ddoiron-cidco commented on import_dfo_data.py
> +if len(sys.argv) == 6:
je comprend pas ce que tu veut dire

2022-04-20 18:05 UTC, Ddoiron-cidco commented on import_dfo_data.py
> +def main_script(arg_host, arg_user, arg_password, arg_database, arg_filename):
je comprend pas ce que tu veut dire

2022-04-26 17:16 UTC, merged